### ISSUE TITLE
Path error (for linux users)

### ISSUE THREAD

**Issue by That-Dude** [Zetaphor/PromptHub#1]
RuntimeError: File at path .../stable-diffusion-webui/extensions/promptHub/ui.html does not exist

When I installed using Automatic1111 as described in the readme, the install folder was 'PromptHub' with a capital 'P'

Renaming the folder with a lowercase 'p' appears to work (I've not tested any other functionality yet).

**Comment by Zetaphor** [comment]
Good catch, I'll get a quick fix pushed for that right now. 

FYI, things are also broke if you pull the latest Automatic1111 as they just upgraded to a new version of Gradio. I'm working on fixing that as well

**Comment by Zetaphor** [comment]
I've pushed a fix for this issue, I still need to address everything being broken with the new Gradio
